OMEGA_UNICODE = u"\u03C9"
MU_UNICODE = u"\u03BC"
XI_UNICODE = u"\u03BE"
KAPPA_UNICODE = u"\u03BA"
BETA_UNICODE = u"\u03B2"
SIGMA_UNICODE = u"\u03C3"


SUBSCRIPT_ONE = u"\u2081"
SUBSCRIPT_TWO = u"\u2082"
SUBSCRIPT_THREE = u"\u2083"

#-------------------------------------------------------------------------------
#                              User define variables
#-------------------------------------------------------------------------------
#                           ELASTIC MODULUS
EMODUL_XX = "E" + SUBSCRIPT_ONE + SUBSCRIPT_ONE
EMODUL_XY = "E" + SUBSCRIPT_ONE + SUBSCRIPT_TWO
EMODUL_XZ = "E" + SUBSCRIPT_ONE + SUBSCRIPT_THREE

EMODUL_YX = "E" + SUBSCRIPT_TWO + SUBSCRIPT_ONE
EMODUL_YY = "E" + SUBSCRIPT_TWO + SUBSCRIPT_TWO
EMODUL_YZ = "E" + SUBSCRIPT_TWO + SUBSCRIPT_THREE

EMODUL_ZX = "E" + SUBSCRIPT_THREE + SUBSCRIPT_ONE
EMODUL_ZY = "E" + SUBSCRIPT_THREE + SUBSCRIPT_TWO
EMODUL_ZZ = "E" + SUBSCRIPT_THREE + SUBSCRIPT_THREE


#                               SIGMAS
SIGMA_XX = SIGMA_UNICODE + SUBSCRIPT_ONE + SUBSCRIPT_ONE
SIGMA_XY = SIGMA_UNICODE + SUBSCRIPT_ONE + SUBSCRIPT_TWO
SIGMA_XZ = SIGMA_UNICODE + SUBSCRIPT_ONE + SUBSCRIPT_THREE

SIGMA_YX = SIGMA_UNICODE + SUBSCRIPT_TWO + SUBSCRIPT_ONE
SIGMA_YY = SIGMA_UNICODE + SUBSCRIPT_TWO + SUBSCRIPT_TWO
SIGMA_YZ = SIGMA_UNICODE + SUBSCRIPT_TWO + SUBSCRIPT_THREE

SIGMA_ZX = SIGMA_UNICODE + SUBSCRIPT_THREE + SUBSCRIPT_ONE
SIGMA_ZY = SIGMA_UNICODE + SUBSCRIPT_THREE + SUBSCRIPT_TWO
SIGMA_ZZ = SIGMA_UNICODE + SUBSCRIPT_THREE + SUBSCRIPT_THREE
